ALTER TABLE bot
ADD COLUMN take_profit_check_value DOUBLE PRECISION DEFAULT 0.85,
ADD COLUMN pullback_threshold DOUBLE PRECISION DEFAULT 3.0,
ADD COLUMN max_trade_hours INT DEFAULT 12;

ALTER TABLE trade
ADD COLUMN highest_price DOUBLE PRECISION;